# Generated by Django 5.1.7 on 2025-11-29 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('adresse_mail', models.CharField(max_length=100)),
                ('mdp', models.TextField()),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_mood', models.DateField()),
                ('hydratation', models.IntegerField()),
                ('activite', models.IntegerField()),
                ('sommeil', models.IntegerField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mood.utilisateur')),
            ],
            options={
                'db_table': 'tracking',
            },
        ),
    ]
